import pytz

INSTALLED_STRIPS = 6
AUTH_MODE_PIN = 1
AUTH_MODE_CARD = 2
AUTH_MODE_BIO = 3
AUTH_MODE_WEB = 4

AUTH_RESULT_SUCCESS = 0
AUTH_RESULT_FAILED = 1

EVENT_TYPE_EVENT = 1
EVENT_TYPE_ALARM = 2

MAIN_DOOR_LOCK = 0
MAIN_DOOR_UN_LOCK = 1

SLOT_STATUS_KEY_NOT_PRESENT = 0
SLOT_STATUS_KEY_PRESENT_RIGHT_SLOT = 1
SLOT_STATUS_KEY_PRESENT_WRONG_SLOT = 2

ACTIVITY_ALLOWED = 0
ACTIVITY_ERROR_USER_INVALID = 1
ACTIVITY_ERROR_TIME_INVALID = 2
ACTIVITY_ERROR_WEEKDAY_INVALID = 3
ACTIVITY_ERROR_FREQUENCY_EXCEEDED = 4
ACTIVITY_ERROR_CODE_INCORRECT = 5

EVENT_LOGIN_SUCCEES = 1
EVENT_LOGIN_FAILED = 2
EVENT_ACTIVITY_CODE_CORRECT = 3
EVENT_ACTIVITY_CODE_WRONG = 4
EVENT_ACTIVITY_CODE_NOT_ALLOWED = 5
EVENT_DOOR_OPEN = 6
EVENT_DOOR_CLOSED = 7
EVENT_DOOR_OPENED_TOO_LONG = 8
EVENT_KEY_TAKEN_CORRECT = 9

EVENT_KEY_TAKEN_WRONG = 10
EVENT_KEY_RETURNED_RIGHT_SLOT = 11
EVENT_KEY_RETURNED_WRONG_SLOT = 12
EVENT_ACTIVITY_CODE_TIMEOUT = 13
EVENT_EMERGENCY_DOOR_OPEN = 14
EVENT_PEG_REGISTRATION_INITIALISED = 15
EVENT_PEG_REGISTRATION_FAILED = 16
EVENT_CARD_ASSIGNMENT_SUCCESS = 17
EVENT_CARD_ASSIGNMENT_FAILURE = 18
EVENT_IP_ADDRESS_CHANGE_INITIALISED = 28
EVENT_IP_ADDRESS_CHANGE_FAILED = 29
EVENT_BIO_REGISTRAION_INITIALISED = 21
EVENT_BIO_REGISTRAION_FAILED = 22

EVENT_ALARM_GENERATION_KEY_TAKEN_TOO_LONG = 23
EVENT_KEY_TAKEN_TOO_LONG_ACK = 24
EVENT_ALARM_GENERATION_WRONG_KEY_PLACED_TOO_LONG = 25
EVENT_WRONG_KEY_PLACED_TOO_LONG_ACK = 26


IS_KEY_IN_WRONG_SLOT = None
IS_KEY_IN_WRONG_SLOT_Correct_Strip = None
IS_KEY_IN_WRONG_SLOT_Correct_Pos = None
IS_KEY_IN_WRONG_SLOT_Wrong_Strip = None
IS_KEY_IN_WRONG_SLOT_Wrong_Pos = None
IS_KEY_IN_WRONG_SLOT_User_PIN = None
IS_KEY_IN_WRONG_SLOT_Message = None

TZ_INDIA = pytz.timezone("Asia/Kolkata")

KEY_DICT = {
    "2": 1,
    "5": 2,
    "8": 3,
    "3": 4,
    "6": 5,
    "9": 6,
    "4": 7,
    "7": 8,
    "10": 9,
    "108": 0,
    "103": "F1",
    "479": "F2",
    "28": ".",
    "465": "UP",
    "11": "DN",
    "55": "ENTER",
}
